spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportsgeekdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB

server:
  port: 8081

## MULTIPART (MultipartProperties)
# Enable multipart uploads
#db:
#  queries:
#    listOfVenue: SELECT VenueId,Name FROM Venue